/* automatically generated by rust-bindgen 0.59.2 */

pub type __int32_t = ::std::os::raw::c_int;
pub type __int64_t = ::std::os::raw::c_long;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TF_KernelBuilder {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TF_OpKernelConstruction {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TF_OpKernelContext {
    _unused: [u8; 0],
}
extern "C" {
    pub fn TF_OpKernelConstruction_Failure(
        ctx: *mut TF_OpKernelConstruction,
        status: *mut TF_Status,
    );
}
extern "C" {
    pub fn TF_OpKernelConstruction_GetAttrSize(
        ctx: *mut TF_OpKernelConstruction,
        attr_name: *const ::std::os::raw::c_char,
        list_size: *mut i32,
        total_size: *mut i32,
        status: *mut TF_Status,
    );
}
extern "C" {
    pub fn TF_OpKernelConstruction_GetAttrType(
        ctx: *mut TF_OpKernelConstruction,
        attr_name: *const ::std::os::raw::c_char,
        val: *mut TF_DataType,
        status: *mut TF_Status,
    );
}
extern "C" {
    pub fn TF_OpKernelConstruction_GetAttrInt32(
        ctx: *mut TF_OpKernelConstruction,
        attr_name: *const ::std::os::raw::c_char,
        val: *mut i32,
        status: *mut TF_Status,
    );
}
extern "C" {
    pub fn TF_OpKernelConstruction_GetAttrInt64(
        ctx: *mut TF_OpKernelConstruction,
        attr_name: *const ::std::os::raw::c_char,
        val: *mut i64,
        status: *mut TF_Status,
    );
}
extern "C" {
    pub fn TF_OpKernelConstruction_GetAttrFloat(
        ctx: *mut TF_OpKernelConstruction,
        attr_name: *const ::std::os::raw::c_char,
        val: *mut f32,
        status: *mut TF_Status,
    );
}
extern "C" {
    pub fn TF_OpKernelConstruction_GetAttrBool(
        ctx: *mut TF_OpKernelConstruction,
        attr_name: *const ::std::os::raw::c_char,
        val: *mut ::std::os::raw::c_uchar,
        status: *mut TF_Status,
    );
}
extern "C" {
    pub fn TF_OpKernelConstruction_GetAttrString(
        ctx: *mut TF_OpKernelConstruction,
        attr_name: *const ::std::os::raw::c_char,
        val: *mut ::std::os::raw::c_char,
        max_length: usize,
        status: *mut TF_Status,
    );
}
extern "C" {
    pub fn TF_OpKernelConstruction_GetAttrTensor(
        ctx: *mut TF_OpKernelConstruction,
        attr_name: *const ::std::os::raw::c_char,
        val: *mut *mut TF_Tensor,
        status: *mut TF_Status,
    );
}
extern "C" {
    pub fn TF_OpKernelConstruction_GetAttrTypeList(
        ctx: *mut TF_OpKernelConstruction,
        attr_name: *const ::std::os::raw::c_char,
        vals: *mut TF_DataType,
        max_vals: ::std::os::raw::c_int,
        status: *mut TF_Status,
    );
}
extern "C" {
    pub fn TF_OpKernelConstruction_GetAttrInt32List(
        ctx: *mut TF_OpKernelConstruction,
        attr_name: *const ::std::os::raw::c_char,
        vals: *mut i32,
        max_vals: ::std::os::raw::c_int,
        status: *mut TF_Status,
    );
}
extern "C" {
    pub fn TF_OpKernelConstruction_GetAttrInt64List(
        ctx: *mut TF_OpKernelConstruction,
        attr_name: *const ::std::os::raw::c_char,
        vals: *mut i64,
        max_vals: ::std::os::raw::c_int,
        status: *mut TF_Status,
    );
}
extern "C" {
    pub fn TF_OpKernelConstruction_GetAttrFloatList(
        ctx: *mut TF_OpKernelConstruction,
        attr_name: *const ::std::os::raw::c_char,
        vals: *mut f32,
        max_vals: ::std::os::raw::c_int,
        status: *mut TF_Status,
    );
}
extern "C" {
    pub fn TF_OpKernelConstruction_GetAttrBoolList(
        ctx: *mut TF_OpKernelConstruction,
        attr_name: *const ::std::os::raw::c_char,
        vals: *mut ::std::os::raw::c_uchar,
        max_vals: ::std::os::raw::c_int,
        status: *mut TF_Status,
    );
}
extern "C" {
    pub fn TF_OpKernelConstruction_GetAttrStringList(
        ctx: *mut TF_OpKernelConstruction,
        attr_name: *const ::std::os::raw::c_char,
        vals: *mut *mut ::std::os::raw::c_char,
        lengths: *mut usize,
        max_values: ::std::os::raw::c_int,
        storage: *mut ::std::os::raw::c_void,
        storage_size: usize,
        status: *mut TF_Status,
    );
}
extern "C" {
    pub fn TF_OpKernelConstruction_GetAttrTensorList(
        ctx: *mut TF_OpKernelConstruction,
        attr_name: *const ::std::os::raw::c_char,
        vals: *mut *mut TF_Tensor,
        max_values: ::std::os::raw::c_int,
        status: *mut TF_Status,
    );
}
extern "C" {
    pub fn TF_OpKernelConstruction_HasAttr(
        ctx: *mut TF_OpKernelConstruction,
        attr_name: *const ::std::os::raw::c_char,
        status: *mut TF_Status,
    ) -> bool;
}
extern "C" {
    pub fn TF_OpKernelConstruction_GetName(ctx: *mut TF_OpKernelConstruction) -> TF_StringView;
}
extern "C" {
    pub fn TF_AllocateOutput(
        context: *mut TF_OpKernelContext,
        index: ::std::os::raw::c_int,
        dtype: TF_DataType,
        dims: *const i64,
        num_dims: ::std::os::raw::c_int,
        len: usize,
        status: *mut TF_Status,
    ) -> *mut TF_Tensor;
}
extern "C" {
    pub fn TF_ForwardInputOrAllocateOutput(
        context: *mut TF_OpKernelContext,
        candidate_input_indices: *const ::std::os::raw::c_int,
        num_candidate_input_indices: ::std::os::raw::c_int,
        output_index: ::std::os::raw::c_int,
        output_dims: *const i64,
        output_num_dims: ::std::os::raw::c_int,
        forwarded_input: *mut ::std::os::raw::c_int,
        status: *mut TF_Status,
    ) -> *mut TF_Tensor;
}
extern "C" {
    pub fn TF_AllocateTemp(
        context: *mut TF_OpKernelContext,
        dtype: TF_DataType,
        dims: *const i64,
        num_dims: ::std::os::raw::c_int,
        alloc_attrs: *mut TF_AllocatorAttributes,
        status: *mut TF_Status,
    ) -> *mut TF_Tensor;
}
